#spring
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.6.103:3306/dota2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    host: 192.168.6.103
    password: 123456
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
    database: 15
log:
  path: /usr/logs/dota2/test
  level: INFO
yurwisher:
  token:
    header-name: X-TOKEN
    enable: true
    secret: wahaha123
    custom-token-class: pers.yurwisher.dota2.common.wrapper.TokenPlus
  qiniu:
    accessKey:
    secretKey:
    #默认目标空间
    bucket:
    zone: zone2
    #自定义响应
    returnBody: "{\"fileUrl\":\"$(year)/$(mon)/$(day)/$(etag)${ext}\"}"
    expires: 3600
    #自定义文件资源名
    saveKey: "$(year)/$(mon)/$(day)/$(etag)${ext}"
  dota2:
    #验证码长宽设置单位px
    valid-code-width: 110
    valid-code-height: 40
    #注册短信内容设置
    register-content: 注册验证码[%1$s]用于注册DOTA2，该验证码5分钟内有效。【DOTA2】
    #重置密码短信内容设置
    retrieve-password-content: 您好，您在DOTA2的账号正在进行找回密码操作，切勿将验证码泄露于他人，5分钟内有效。验证码：[%1$s] 。【DOTA2】
server:
  port: 8111

